"use client";
import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type RequestRow={id:string;sender_id:string;recipient_id:string;status:string;created_at:string;game_id:string|null};

export default function PvpPage(){
 const supabase=createClient();
 const [username,setUsername]=useState(""); const [sent,setSent]=useState(""); const [error,setError]=useState(""); const [requests,setRequests]=useState<RequestRow[]>([]); const [loading,setLoading]=useState(false);
 const loadRequests=useCallback(async()=>{const {data:claims}=await supabase.auth.getClaims();const id=claims?.claims?.sub as string|undefined;if(!id)return;const {data}=await supabase.from("pvp_game_requests").select("id,sender_id,recipient_id,status,created_at,game_id").eq("recipient_id",id).eq("status","pending").order("created_at",{ascending:false});setRequests((data||[]) as RequestRow[]);},[supabase]);
 useEffect(()=>{loadRequests();},[loadRequests]);
 async function sendRequest(){setError("");setSent("");setLoading(true);try{const name=username.trim();if(name.length<3)throw new Error("Enter a valid username.");const {data:claims}=await supabase.auth.getClaims();const me=claims?.claims?.sub as string|undefined;if(!me)throw new Error("Sign in to challenge a friend.");const {data:found,error:findError}=await supabase.rpc("find_profile_by_username",{target_username:name});if(findError)throw findError;if(!found?.length)throw new Error("Player not found.");if(found[0].id===me)throw new Error("You cannot challenge yourself.");const {error:insertError}=await supabase.from("pvp_game_requests").insert({sender_id:me,recipient_id:found[0].id});if(insertError)throw insertError;setSent(`Challenge sent to ${found[0].username}.`);setUsername("");}catch(e){setError(e instanceof Error?e.message:"Could not send challenge.");}finally{setLoading(false);loadRequests();}}
 async function accept(requestId:string){setError("");setLoading(true);try{const {data,error:fnError}=await supabase.functions.invoke("pvp-game",{body:{action:"accept",request_id:requestId}});if(fnError)throw fnError;if(!data?.game_id)throw new Error("Game could not be created.");window.location.href=`/pvp/${data.game_id}`;}catch(e){setError(e instanceof Error?e.message:"Could not accept challenge.");}finally{setLoading(false);loadRequests();}}
 return <div className="cr-shell"><nav className="cr-nav"><a href="/" className="cr-brand"><span className="cr-mark">♞</span><span>ChessRankers</span></a><div className="cr-links"><a href="/play">Play AI</a><a href="/solo">Solo Chess</a><a className="active" href="/pvp">Play a Friend</a><a href="/tester">Move Tester</a><a href="/leaderboard">Leaderboard</a><a href="/profile">Profile</a></div></nav><main className="chess-page"><div className="match-top"><div><h1>Play a Friend</h1><p>Private PvP only. Challenge another account directly.</p></div><span className="mode-pill">NO ELO</span></div><div className="cr-feature-grid"><section className="cr-card"><h2>Private challenge</h2><p>PvP never changes Chess Elo or Solo Elo. It only records PvP wins, losses and draws.</p><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Friend's username" style={{width:"100%",padding:13,borderRadius:10,border:"1px solid var(--line)",background:"var(--panel)",margin:"14px 0"}}/><button disabled={loading} className="cr-btn primary" onClick={sendRequest}>{loading?"Working…":"Send request"}</button>{sent&&<p style={{color:"var(--accent)"}}>{sent}</p>}{error&&<p style={{color:"#ef8b8b"}}>{error}</p>}</section><section className="cr-card"><h2>Incoming challenges</h2>{requests.length?requests.map(r=><div className="move-row" key={r.id}><span>Private challenge</span><span>{new Date(r.created_at).toLocaleDateString()}</span><button disabled={loading} className="control" onClick={()=>accept(r.id)}>Accept</button></div>):<p className="cr-note">No pending challenges.</p>}</section></div><p className="cr-note">PvP is deliberately excluded from both Elo leaderboards and normal Chess W/D/L. Accepted games are private to their two players.</p></main></div>}
