"use client";
import { useState } from "react";
import { Chess } from "chess.js";
import ChessBoard from "@/components/chess-board";

const puzzles=["6k1/5pp1/8/8/3p4/8/5PPP/6K1 w - - 0 1","7k/6pp/8/3Q4/8/8/6PP/6K1 w - - 0 1","6k1/5pp1/4p3/8/3P4/5P2/6P1/6K1 w - - 0 1"];
export default function SoloPage(){
 const [index,setIndex]=useState(0); const [game,setGame]=useState(()=>new Chess(puzzles[0])); const [score,setScore]=useState(0); const [status,setStatus]=useState("Find the strongest capture");
 function move(san:string){setStatus(san?"Position updated — keep solving":"Your move");setScore(v=>v+1);}
 function next(){const n=(index+1)%puzzles.length;setIndex(n);setGame(new Chess(puzzles[n]));setStatus("Find the strongest capture");}
 return <div className="cr-shell"><nav className="cr-nav"><a href="/" className="cr-brand"><span className="cr-mark">♞</span><span>ChessRankers</span></a><div className="cr-links"><a href="/play">Play AI</a><a className="active" href="/solo">Solo Chess</a><a href="/pvp">Play a Friend</a><a href="/tester">Move Tester</a><a href="/leaderboard">Leaderboard</a><a href="/profile">Profile</a></div></nav><main className="chess-page"><div className="match-top"><div><h1>Solo Chess</h1><p>Capture puzzles · separate Solo Elo · never mixed with Chess Elo or PvP.</p></div><span className="mode-pill">SOLO ELO</span></div><section className="match-layout"><div className="board-wrap"><div className="player-card" style={{marginBottom:10}}><div className="player-line"><span className="player-name">Solo Arena</span><span className="player-rating">Puzzle {index+1}/{puzzles.length}</span></div><div className="clock active">Score {score}</div></div><ChessBoard game={game} onMove={move}/><div className="board-meta"><span>{status}</span><strong>Solo Elo starts at 0</strong></div></div><aside className="side-stack"><div className="info-card"><h3>How Solo Elo works</h3><p style={{color:"var(--muted)",lineHeight:1.6,fontSize:13}}>Your Solo rating is calculated only from completed Solo runs. Material, checks, captures, threats, activity, king safety, position, thinking time and challenge factors are kept separate from normal Chess Elo.</p></div><div className="info-card"><h3>Run controls</h3><div className="controls"><button className="control" onClick={()=>{setGame(new Chess(puzzles[index]));setStatus("Find the strongest capture")}}>Reset</button><button className="control" onClick={next}>Next puzzle</button></div></div><div className="info-card"><h3>Rating status</h3><strong>0 Solo Elo</strong><p className="cr-note">No rating is awarded by this local puzzle preview until the server-side run validator is connected.</p></div></aside></section></main></div>;
}
