"use client";
import { useEffect, useMemo, useState } from "react";
import { Chess } from "chess.js";
import { createClient } from "@/lib/supabase/client";
import ChessBoard from "@/components/chess-board";

export default function PvpGame({ gameId }: { gameId: string }) {
 const supabase=createClient(); const [game,setGame]=useState(()=>new Chess()); const [moves,setMoves]=useState<string[]>([]); const [status,setStatus]=useState("Loading game…"); const [myColor,setMyColor]=useState<"w"|"b"|null>(null); const [result,setResult]=useState<string|null>(null); const [error,setError]=useState("");
 async function refresh(){const {data:claims}=await supabase.auth.getClaims();const me=claims?.claims?.sub as string|undefined;if(!me)return;const {data,rowError}=await supabase.from("pvp_games").select("white_player_id,black_player_id,status,result,moves").eq("id",gameId).maybeSingle();if(rowError||!data){setError("Private game not found.");return;}setMyColor(data.white_player_id===me?"w":data.black_player_id===me?"b":null);const next=new Chess();const sans=(Array.isArray(data.moves)?data.moves:[]).map((m:any)=>String(m.san));try{for(const san of sans)next.move(san);}catch{setError("Game data is invalid.");return;}setGame(next);setMoves(sans);setResult(data.result);setStatus(data.status==="completed"?(data.result==="draw"?"Draw":data.result===(data.white_player_id===me?"white":"black")?"You won":"You lost"):next.turn()===(data.white_player_id===me?"w":"b")?"Your move":"Opponent's move");}
 useEffect(()=>{refresh();const channel=supabase.channel(`pvp:${gameId}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"pvp_games",filter:`id=eq.${gameId}`},()=>refresh()).subscribe();return()=>{supabase.removeChannel(channel);};},[gameId]);
 async function onMove(_san:string,next:Chess){if(!myColor||next.history().length!==moves.length+1)return;const san=next.history().at(-1)!;const {data,error:fnError}=await supabase.functions.invoke("pvp-game",{body:{action:"move",game_id:gameId,san}});if(fnError||!data){setError(fnError?.message||"Move rejected.");await refresh();return;}setGame(next);setMoves(data.moves.map((m:any)=>m.san));setResult(data.result);setStatus(data.status==="completed"?"Game complete":next.turn()===myColor?"Your move":"Opponent's move");}
 async function resign(){const {error:fnError}=await supabase.functions.invoke("pvp-game",{body:{action:"resign",game_id:gameId}});if(fnError)setError(fnError.message);else await refresh();}
 const canMove=Boolean(myColor&&game.turn()===myColor&&!result); const moveRows=useMemo(()=>moves.map((m,i)=>({n:Math.floor(i/2)+1,move:m,color:i%2?"b":"w"})),[moves]);
 return <div className="cr-shell"><nav className="cr-nav"><a href="/" className="cr-brand"><span className="cr-mark">♞</span><span>ChessRankers</span></a><div className="cr-links"><a href="/play">Play AI</a><a href="/solo">Solo Chess</a><a className="active" href="/pvp">Play a Friend</a><a href="/leaderboard">Leaderboard</a><a href="/profile">Profile</a></div></nav><main className="chess-page"><div className="match-top"><div><h1>Private PvP Match</h1><p>{myColor==="w"?"You are White":myColor==="b"?"You are Black":"Checking private access…"} · No Elo</p></div><span className="mode-pill">PVP</span></div><section className="match-layout"><div className="board-wrap"><ChessBoard game={game} orientation={myColor==="b"?"black":"white"} onMove={canMove?onMove:undefined}/><div className="board-meta"><span>{status}</span><strong>{result?`Result: ${result}`:"Private game"}</strong></div></div><aside className="side-stack"><div className="info-card"><h3>Game controls</h3><p className="cr-note">PvP is completely separate from Chess Elo and Solo Elo.</p><button className="control" onClick={resign} disabled={!myColor||Boolean(result)}>Resign</button><a className="control" href="/pvp" style={{display:"inline-block",marginLeft:8}}>Back</a>{error&&<p style={{color:"#ef8b8b",fontSize:12}}>{error}</p>}</div><div className="info-card"><h3>Moves</h3><div className="move-list">{moveRows.map((r)=><div className="move-row" key={`${r.n}-${r.color}`}><span>{r.color==="w"?`${r.n}.`:""}</span><span>{r.move}</span></div>)}</div></div></aside></section></main></div>;
}
